#!/usr/bin/env python3
"""Copy pixel-art bird images into frontend/public/birds/ and emit the
common-name → URL map at frontend/src/services/birdImages.js.

One-shot dev tool. Run from the repo root after adding/removing source images:

    python3 scripts/build_bird_images.py [--source PATH]

The script wipes any slug files in frontend/public/birds/ that aren't in the
freshly-generated map, so re-runs stay clean.
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_SOURCE = Path("/Users/pranavbalasubramanian/nanoBirdImageGen/downscaled")
LABELS_FILE = REPO_ROOT / "backend" / "model" / "BirdNET_GLOBAL_6K_V2.4_Labels_en.txt"
OUT_DIR = REPO_ROOT / "frontend" / "public" / "birds"
MAP_FILE = REPO_ROOT / "frontend" / "src" / "services" / "birdImages.js"

VALID_EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def slugify(name: str) -> str:
    s = name.lower().replace("'", "")
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


def load_birdnet_common_names() -> set[str]:
    common = set()
    with LABELS_FILE.open() as f:
        for line in f:
            line = line.strip()
            if "_" in line:
                common.add(line.split("_", 1)[1])
    return common


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE,
                        help=f"pixel-art source directory (default: {DEFAULT_SOURCE})")
    args = parser.parse_args()

    if not args.source.is_dir():
        print(f"error: source directory not found: {args.source}", file=sys.stderr)
        return 1
    if not LABELS_FILE.is_file():
        print(f"error: labels file not found: {LABELS_FILE}", file=sys.stderr)
        return 1

    birdnet_names = load_birdnet_common_names()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    mapping: dict[str, str] = {}
    skipped: list[str] = []

    for src in sorted(args.source.iterdir()):
        if not src.is_file() or src.suffix.lower() not in VALID_EXTS:
            continue
        common_name = src.stem
        if common_name not in birdnet_names:
            print(f"  skip  {common_name}: not in BirdNET labels")
            skipped.append(common_name)
            continue
        slug = slugify(common_name) + src.suffix.lower()
        dest = OUT_DIR / slug
        shutil.copy2(src, dest)
        mapping[common_name] = f"/birds/{slug}"

    # Wipe stale slugs from previous runs
    kept = {Path(url).name for url in mapping.values()}
    for existing in OUT_DIR.iterdir():
        if existing.is_file() and existing.name not in kept:
            existing.unlink()

    # Emit the JS module (sorted for stable diffs)
    sorted_map = dict(sorted(mapping.items()))
    body = ",\n".join(f"  {json.dumps(k)}: {json.dumps(v)}" for k, v in sorted_map.items())
    MAP_FILE.parent.mkdir(parents=True, exist_ok=True)
    MAP_FILE.write_text(
        "// Auto-generated by scripts/build_bird_images.py — do not edit by hand.\n"
        "const birdImages = Object.freeze({\n"
        f"{body},\n"
        "});\n"
        "export default birdImages;\n"
    )

    print(f"\nMapped: {len(mapping)} · Skipped (not in BirdNET): {len(skipped)}")
    print(f"  images → {OUT_DIR.relative_to(REPO_ROOT)}")
    print(f"  map    → {MAP_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
